# Generated by Django 5.2.4 on 2026-07-19 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('machinery', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='machine',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='site',
            options={'ordering': ['name']},
        ),
    ]
