# Generated by Django 5.2.4 on 2026-07-19 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_seed_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='assigned_site',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
