# Generated by Django 5.2.4 on 2026-07-18 12:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('machinery', '0002_initial'),
        ('maintenance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenanceteam',
            name='lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='led_maintenance_teams', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='maintenancehistory',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_records', to='maintenance.maintenanceteam'),
        ),
        migrations.AddField(
            model_name='maintenanceteammember',
            name='team',
            field=models.ForeignKey(db_column='team_id', on_delete=django.db.models.deletion.CASCADE, to='maintenance.maintenanceteam'),
        ),
        migrations.AddField(
            model_name='maintenanceteammember',
            name='user',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='maintenanceteam',
            name='members',
            field=models.ManyToManyField(related_name='maintenance_teams', through='maintenance.MaintenanceTeamMember', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='servicehistory',
            name='machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_records', to='machinery.machine'),
        ),
        migrations.AddField(
            model_name='serviceteam',
            name='lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='led_service_teams', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='servicehistory',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_records', to='maintenance.serviceteam'),
        ),
        migrations.AddField(
            model_name='serviceteammember',
            name='team',
            field=models.ForeignKey(db_column='team_id', on_delete=django.db.models.deletion.CASCADE, to='maintenance.serviceteam'),
        ),
        migrations.AddField(
            model_name='serviceteammember',
            name='user',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='serviceteam',
            name='members',
            field=models.ManyToManyField(related_name='service_teams', through='maintenance.ServiceTeamMember', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='maintenanceteammember',
            unique_together={('team', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='serviceteammember',
            unique_together={('team', 'user')},
        ),
    ]
