# Generated by Django 5.2.4 on 2026-07-19 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('machine_code', models.CharField(max_length=50)),
                ('machine_name', models.CharField(max_length=100)),
                ('site', models.CharField(max_length=100)),
                ('priority', models.CharField(max_length=20)),
                ('assigned_time', models.CharField(blank=True, max_length=50, null=True)),
                ('eta', models.CharField(blank=True, max_length=50, null=True)),
                ('assigned_by', models.CharField(blank=True, max_length=100, null=True)),
                ('problem', models.TextField()),
                ('status', models.CharField(default='Waiting', max_length=50)),
                ('temp', models.FloatField(blank=True, null=True)),
                ('oil_pressure', models.FloatField(blank=True, null=True)),
                ('vibration', models.FloatField(blank=True, null=True)),
                ('hours', models.FloatField(blank=True, null=True)),
                ('rul', models.FloatField(blank=True, null=True)),
                ('failure_prediction', models.CharField(blank=True, max_length=255, null=True)),
                ('required_parts', models.JSONField(blank=True, default=list)),
                ('instructions', models.JSONField(blank=True, default=list)),
                ('engineer_notes', models.TextField(blank=True, default='', null=True)),
                ('images', models.JSONField(blank=True, default=list)),
                ('ai_recommendations', models.JSONField(blank=True, default=list)),
                ('health_before', models.FloatField(blank=True, null=True)),
                ('last_service_date', models.CharField(blank=True, max_length=50, null=True)),
                ('time_generated', models.CharField(blank=True, max_length=50, null=True)),
                ('inspection_status', models.CharField(default='NONE', max_length=20)),
                ('service_engineer', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('completion_time', models.CharField(blank=True, max_length=50, null=True)),
                ('status_history', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'work_orders',
                'ordering': ['created_at'],
            },
        ),
    ]
