# Generated by Django 5.2.4 on 2026-07-19 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0003_workorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='health_after',
            field=models.IntegerField(blank=True, default=91, null=True),
        ),
        migrations.AddField(
            model_name='workorder',
            name='parts_replaced',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='workorder',
            name='repair_cost',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='workorder',
            name='time_taken',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
