# Generated by Django 5.2.4 on 2026-07-19 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0004_workorder_health_after_workorder_parts_replaced_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='failure_probability',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
